const Asteroid = require('./asteroid.js');
const Asteroids = require('./asteroids.js');
// const Bullet = require('./bullet.js');
const GameView = require('./game_view.js');
const Game = require('./game.js');
const MovingObject = require('./moving_object.js');
// const Ship = require('./ship.js');
const Util = require('./utils.js');
window.Asteroid = Asteroid;
